[C++23] art: Add missing header
Fixes build failures with C++23 by adding explicit includes
for standard library components that are no longer transitively
included. Specifically, add stack to dump_trace.cc.

Errors:
art/test/2246-trace-v2/dump_trace.cc:217:19: error: implicit
instantiation of undefined template 'std::stack<unsigned long long>'
  217 |       method_stack.push(method_id);

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libarttest
Change-Id: I3fa5fcbded027d71369521433510f4ac732e17d6