Fix -Wthread-safety-analysis in subtype_check_test.cc
This is to unblock the toolchain update to r596125.

art/runtime/subtype_check_test.cc:348:27: error: mutex 'mutator_lock_' must be acquired before 'subtype_check_lock_' [-Werror,-Wthread-safety-analysis]
  348 |     MockScopedLockMutator lock_b;
      |                           ^

Test: m art_runtime_tests
Bug: 489835449
Flag: EXEMPT PURE_REFACTOR
Change-Id: I7d3c8e65912e928edba0ffee78bfe5c8593e5848