Reduce the number of threads in 2391-virtual-thread-sleep
On art-asan target, the following error causes the test flakiness.

> ERROR: AddressSanitizer: out of memory: failed to allocate 0xb09000 (11571200) bytes of FakeStack (error code: 12)

Flag: EXEMPT TEST_ONLY
Test: 2391-virtual-thread-sleep
Change-Id: I447dc09309c10c926d13df45307581e8535d7be2